/*
 * RNN Model -- Arduino verification sketch
 * Generated automatically -- do not edit the weights.
 *
 * VERIFICATION GUIDE
 * -------------------
 * Input  seq_len    : 4
 * Input  input_size : 2
 * Input values (same order as the flat array below):
 *   t=0: [1.76405239, 0.40015721]
 *   t=1: [0.97873801, 2.24089313]
 *   t=2: [1.86755800, -0.97727787]
 *   t=3: [0.95008844, -0.15135720]
 *
 * Expected logit    : 10.61098385
 * Expected class    : 1
 *
 * Upload this sketch, open Serial Monitor at 115200 baud,
 * and confirm the printed value matches the expected value
 * above to at least 5 decimal places.
 *
 * Acceptable tolerance: +/-0.00002  (float32 rounding)
 */

#include "RNNModel.h"

RNNModel model;

void setup() {
    Serial.begin(115200);
    while (!Serial);  // Wait for Serial on native-USB boards

    const int SEQ_LEN    = 4;
    const int INPUT_SIZE = 2;

    // Verification input (auto-generated by Python exporter)
    float input[SEQ_LEN * INPUT_SIZE] = {
        1.76405239f, 0.40015721f, 0.97873801f, 2.24089313f, 1.86755800f, -0.97727787f, 0.95008844f, -0.15135720f
    };

    float output = model.predict(input, SEQ_LEN);

    // Expected logit  : 10.61098385
    // Expected class  : 1
    Serial.print("Predicted logit  : "); Serial.println(output, 8);
    Serial.print("Predicted class  : "); Serial.println(output > 0.0f ? 1 : 0);
}

void loop() {
    // Nothing to do here
}