/*
 * GAN Generator -- Arduino verification sketch
 * Generated automatically -- do not edit the weights.
 *
 * VERIFICATION GUIDE
 * -------------------
 * Latent dim  : 16
 * Output dim  : 4
 * Conditional : False
 *
 * Input z (first 8 shown): [1.764052, 0.400157, 0.978738, 2.240893, 1.867558, -0.977278, 0.950088, -0.151357]
 * Expected output (first 8): [-0.483521, -0.286410, 0.603639, -0.506033]
 *
 * Upload this sketch, open Serial Monitor at 115200 baud,
 * and confirm the printed values match to at least 4 decimal places.
 */

#include "GANModel.h"

GANModel model;

void setup() {
    Serial.begin(115200);
    while (!Serial);

    const int LATENT_DIM = 16;
    const int OUTPUT_DIM = 4;

    // Verification latent vector (auto-generated by Python exporter)
    float z[LATENT_DIM] = {
        1.76405239f, 0.40015721f, 0.97873801f, 2.24089313f, 1.86755800f, -0.97727787f, 0.95008844f, -0.15135720f, -0.10321885f, 0.41059852f, 0.14404356f, 1.45427346f, 0.76103771f, 0.12167501f, 0.44386324f, 0.33367434f
    };

    float out[OUTPUT_DIM];
    model.generate(z, out);

    Serial.println("Generated output (first 8 dims):");
    int n_print = OUTPUT_DIM < 8 ? OUTPUT_DIM : 8;
    for (int i = 0; i < n_print; i++) {
        Serial.print("  out["); Serial.print(i);
        Serial.print("] = "); Serial.println(out[i], 6);
    }
}

void loop() {
    // Nothing to do here
}