/*
 * LNN (LTC) Model -- Arduino verification sketch
 * Generated automatically -- do not edit the weights.
 *
 * VERIFICATION GUIDE
 * -------------------
 * Input  seq_len    : 4
 * Input  input_size : 1
 * Input values (same order as the flat array below):
 * t=0: [1.76405239]
 * t=1: [0.40015721]
 * t=2: [0.97873801]
 * t=3: [2.24089313]
 *
 * Expected value    : 1.27840519
 *
 * Upload this sketch, open Serial Monitor at 115200 baud,
 * and confirm the printed value matches the expected value
 * above to at least 5 decimal places.
 *
 * Acceptable tolerance: +/-0.0001  (float32 + Euler rounding)
 */

#include "LNNModel.h"

LNNModel model;

void setup() {
    Serial.begin(115200);
    while (!Serial);

    const int SEQ_LEN    = 4;
    const int INPUT_SIZE = 1;

    // Verification input (auto-generated by Python exporter)
    float input[SEQ_LEN * INPUT_SIZE] = {
        1.76405239f, 0.40015721f, 0.97873801f, 2.24089313f
    };

    // IMPRESCINDÍVEL: Resetar o estado antes de passar a sequência!
    model.reset_states();
    float output = model.predict(input, SEQ_LEN);

    // Expected value  : 1.27840519
    Serial.print("Predicted value  : "); Serial.println(output, 8);
}

void loop() {
    // Nothing to do here
}