/*
 * RNN Model -- Arduino verification sketch
 * Generated automatically -- do not edit the weights.
 *
 * VERIFICATION GUIDE
 * -------------------
 * Input  seq_len    : 4
 * Input  input_size : 1
 * Input values (same order as the flat array below):
 *   t=0: [1.76405239]
 *   t=1: [0.40015721]
 *   t=2: [0.97873801]
 *   t=3: [2.24089313]
 *
 * Expected value    : 0.86626846
 *
 * Upload this sketch, open Serial Monitor at 115200 baud,
 * and confirm the printed value matches the expected value
 * above to at least 5 decimal places.
 *
 * Acceptable tolerance: +/-0.00002  (float32 rounding)
 */

#include "RNNModel.h"

RNNModel model;

void setup() {
    Serial.begin(115200);
    while (!Serial);  // Wait for Serial on native-USB boards

    const int SEQ_LEN    = 4;
    const int INPUT_SIZE = 1;

    // Verification input (auto-generated by Python exporter)
    float input[SEQ_LEN * INPUT_SIZE] = {
        1.76405239f, 0.40015721f, 0.97873801f, 2.24089313f
    };

    float output = model.predict(input, SEQ_LEN);

    // Expected value  : 0.86626846
    Serial.print("Predicted value  : "); Serial.println(output, 8);
}

void loop() {
    // Nothing to do here
}