/*
 * GAN Generator -- Arduino verification sketch
 * Generated automatically -- do not edit the weights.
 *
 * VERIFICATION GUIDE
 * -------------------
 * Latent dim  : 4
 * Output dim  : 2
 * Conditional : True
 * Classes     : 3  (using label=0 for verification)
 *
 * Input z (first 8 shown): [1.764052, 0.400157, 0.978738, 2.240893]
 * Expected output (first 8): [0.745394, 0.139411]
 *
 * Upload this sketch, open Serial Monitor at 115200 baud,
 * and confirm the printed values match to at least 4 decimal places.
 */

#include "GANModel.h"

GANModel model;

void setup() {
    Serial.begin(115200);
    while (!Serial);

    const int LATENT_DIM = 4;
    const int OUTPUT_DIM = 2;

    // Verification latent vector (auto-generated by Python exporter)
    float z[LATENT_DIM] = {
        1.76405239f, 0.40015721f, 0.97873801f, 2.24089313f
    };

    float out[OUTPUT_DIM];
    model.generate(z, 0, out);

    Serial.println("Generated output (first 8 dims):");
    int n_print = OUTPUT_DIM < 8 ? OUTPUT_DIM : 8;
    for (int i = 0; i < n_print; i++) {
        Serial.print("  out["); Serial.print(i);
        Serial.print("] = "); Serial.println(out[i], 6);
    }
}

void loop() {
    // Nothing to do here
}