#pragma once
/*
 * SOMModel.h -- Self-Organizing Map
 * Auto-generated by cpp_generator.py -- do not edit weights manually.
 *
 * Map size    : 8 x 8 = 64 neurons
 * Input dim   : 2
 * Topology    : rectangular
 * Kernel      : gaussian
 * Board       : ESP32
 */

#include <math.h>

// SOM weights: shape [64][2]  (flat row-major: neuron k -> w[k*2 .. k*2+1])
const float som_weights[128] = {
  0.14000621f, 0.50518966f, 0.18698280f, 0.47382209f, 0.25626832f, 0.42596695f, 0.37832847f, 0.36064571f, 0.53646189f, 0.27829266f, 0.62615639f, 0.23072669f, 0.68493652f, 0.20703527f, 0.73344785f, 0.19432311f, 0.16160475f, 0.54296273f, 0.20705234f, 0.51454812f, 0.27848548f, 0.46884710f, 0.40014583f, 0.40189138f, 0.54737347f, 0.32144696f, 0.63687295f, 0.27511019f, 0.70186770f, 0.25350469f, 0.75474304f, 0.24551190f, 0.19462925f, 0.59225303f, 0.23799850f, 0.56901067f, 0.30908838f, 0.53240776f, 0.42471308f, 0.47314918f, 0.56532609f, 0.39059442f, 0.65830064f, 0.33808160f, 0.72814381f, 0.31389299f, 0.77915817f, 0.30605111f, 0.22337322f, 0.64475095f, 0.26690501f, 0.62286556f, 0.34246132f, 0.59296834f, 0.44779027f, 0.55240530f, 0.57109350f, 0.48573473f, 0.66812730f, 0.42424729f, 0.74479318f, 0.38261053f, 0.79481649f, 0.36292550f, 0.24579629f, 0.69251066f, 0.29386652f, 0.67233455f, 0.37794957f, 0.64876187f, 0.46981362f, 0.62628585f, 0.56545788f, 0.59087718f, 0.65324062f, 0.54423898f, 0.73299754f, 0.48944426f, 0.78814077f, 0.44836032f, 0.30015409f, 0.75520766f, 0.35096347f, 0.73652130f, 0.42957556f, 0.71505779f, 0.49782252f, 0.70043957f, 0.56487799f, 0.68472153f, 0.63138002f, 0.66573346f, 0.69612044f, 0.63855845f, 0.75013280f, 0.60595655f, 0.40571868f, 0.84989083f, 0.43451610f, 0.82084870f, 0.47832766f, 0.77915388f, 0.52168286f, 0.75596577f, 0.57087320f, 0.75101113f, 0.62373018f, 0.75625056f, 0.67429107f, 0.76871860f, 0.71687287f, 0.77832061f, 0.46313825f, 0.90236986f, 0.47691801f, 0.87124598f, 0.50211465f, 0.82110995f, 0.53626192f, 0.79086822f, 0.57877272f, 0.79171365f, 0.62500834f, 0.80734724f, 0.67176956f, 0.82994103f, 0.71043867f, 0.85016811f
};

class SOMModel {
public:
  static const int N_NEURONS  = 64;
  static const int INPUT_DIM  = 2;
  static const int N_ROWS     = 8;
  static const int N_COLS     = 8;

  /**
   * Find the Best Matching Unit (BMU) for input vector x.
   *
   * @param x  Input array of length INPUT_DIM.
   * @return   Flat BMU index in [0, N_NEURONS).  Decode with
   *           bmu_row() and bmu_col().
   */
  int predict(const float* x) {
    int   best_k    = 0;
    float best_dist = 3.4028235e+38f;   // FLT_MAX

    for (int k = 0; k < 64; k++) {
      float dist = 0.0f;
      for (int j = 0; j < 2; j++) {
        float diff = x[j] - som_weights[k * 2 + j];
        dist += diff * diff;
        // Early exit: prune if already worse than best
        if (dist >= best_dist) break;
      }
      if (dist < best_dist) {
        best_dist = dist;
        best_k    = k;
      }
    }
    return best_k;
  }

  /** Decode flat BMU index to row coordinate. */
  int bmu_row(int bmu_index) { return bmu_index / N_COLS; }

  /** Decode flat BMU index to column coordinate. */
  int bmu_col(int bmu_index) { return bmu_index % N_COLS; }

  /**
   * Quantize: copy the BMU weight vector into output[].
   *
   * @param bmu_index  Flat BMU index returned by predict().
   * @param output     Caller-allocated array of length INPUT_DIM.
   */
  void quantize(int bmu_index, float* output) {
    int base = bmu_index * 2;
    for (int j = 0; j < 2; j++)
      output[j] = som_weights[base + j];
  }

  /**
   * Quantization error: Euclidean distance from x to its BMU weight.
   *
   * @param x          Input array of length INPUT_DIM.
   * @param bmu_index  Flat BMU index returned by predict().
   * @return           L2 distance (not squared).
   */
  float quantization_error(const float* x, int bmu_index) {
    float proto[INPUT_DIM];
    quantize(bmu_index, proto);
    float sq = 0.0f;
    for (int j = 0; j < 2; j++) {
      float d = x[j] - proto[j];
      sq += d * d;
    }
    return sqrtf(sq);
  }
};