#pragma once
/*
 * SOMModel.h -- Self-Organizing Map
 * Auto-generated by cpp_generator.py -- do not edit weights manually.
 *
 * Map size    : 8 x 8 = 64 neurons
 * Input dim   : 2
 * Topology    : rectangular
 * Kernel      : gaussian
 * Board       : ESP32
 */

#include <math.h>

// SOM weights: shape [64][2]  (flat row-major: neuron k -> w[k*2 .. k*2+1])
const float som_weights[128] = {
  0.71268070f, 0.84873414f, 0.71768445f, 0.77937752f, 0.74754012f, 0.61022240f, 0.78056383f, 0.45479691f, 0.78916800f, 0.37019673f, 0.78173500f, 0.31082469f, 0.75972903f, 0.24832332f, 0.73568249f, 0.19659652f, 0.67323178f, 0.83023131f, 0.67516059f, 0.77102512f, 0.69449204f, 0.64267749f, 0.72525829f, 0.49673083f, 0.73723781f, 0.39323747f, 0.72865641f, 0.32095259f, 0.70533091f, 0.25567296f, 0.68693423f, 0.20830514f, 0.62477434f, 0.81285185f, 0.62346101f, 0.76301503f, 0.62929505f, 0.67344183f, 0.64636183f, 0.55474699f, 0.65909094f, 0.43733412f, 0.65421212f, 0.34645608f, 0.63675535f, 0.27706593f, 0.62732267f, 0.23119175f, 0.57999426f, 0.80173862f, 0.57019728f, 0.76026583f, 0.56149340f, 0.69659638f, 0.55954576f, 0.60756749f, 0.56149131f, 0.50048506f, 0.55772048f, 0.39915928f, 0.54487157f, 0.32424116f, 0.53702193f, 0.27876091f, 0.53938478f, 0.80833417f, 0.52312922f, 0.76806378f, 0.50076252f, 0.71315491f, 0.47280639f, 0.64214760f, 0.44351181f, 0.56369835f, 0.42061922f, 0.47948226f, 0.40001684f, 0.40360269f, 0.37898210f, 0.36075467f, 0.50603223f, 0.84739280f, 0.48177302f, 0.79743415f, 0.43627656f, 0.72682971f, 0.38292038f, 0.65697831f, 0.34200579f, 0.59824520f, 0.30886143f, 0.53651351f, 0.27893853f, 0.46925983f, 0.25648212f, 0.42554241f, 0.47700414f, 0.88464785f, 0.43377826f, 0.83166856f, 0.35147598f, 0.74311912f, 0.29448113f, 0.67435992f, 0.26784468f, 0.62373847f, 0.23872904f, 0.57101864f, 0.20694631f, 0.51479024f, 0.18700801f, 0.47345012f, 0.44804478f, 0.89457363f, 0.38923758f, 0.84075922f, 0.29348356f, 0.75305659f, 0.24530926f, 0.69211853f, 0.22422992f, 0.64368510f, 0.19547245f, 0.59252930f, 0.16188015f, 0.54301912f, 0.14032251f, 0.50497663f
};

class SOMModel {
public:
  static const int N_NEURONS  = 64;
  static const int INPUT_DIM  = 2;
  static const int N_ROWS     = 8;
  static const int N_COLS     = 8;

  /**
   * Find the Best Matching Unit (BMU) for input vector x.
   *
   * @param x  Input array of length INPUT_DIM.
   * @return   Flat BMU index in [0, N_NEURONS).  Decode with
   *           bmu_row() and bmu_col().
   */
  int predict(const float* x) {
    int   best_k    = 0;
    float best_dist = 3.4028235e+38f;   // FLT_MAX

    for (int k = 0; k < 64; k++) {
      float dist = 0.0f;
      for (int j = 0; j < 2; j++) {
        float diff = x[j] - som_weights[k * 2 + j];
        dist += diff * diff;
        // Early exit: prune if already worse than best
        if (dist >= best_dist) break;
      }
      if (dist < best_dist) {
        best_dist = dist;
        best_k    = k;
      }
    }
    return best_k;
  }

  /** Decode flat BMU index to row coordinate. */
  int bmu_row(int bmu_index) { return bmu_index / N_COLS; }

  /** Decode flat BMU index to column coordinate. */
  int bmu_col(int bmu_index) { return bmu_index % N_COLS; }

  /**
   * Quantize: copy the BMU weight vector into output[].
   *
   * @param bmu_index  Flat BMU index returned by predict().
   * @param output     Caller-allocated array of length INPUT_DIM.
   */
  void quantize(int bmu_index, float* output) {
    int base = bmu_index * 2;
    for (int j = 0; j < 2; j++)
      output[j] = som_weights[base + j];
  }

  /**
   * Quantization error: Euclidean distance from x to its BMU weight.
   *
   * @param x          Input array of length INPUT_DIM.
   * @param bmu_index  Flat BMU index returned by predict().
   * @return           L2 distance (not squared).
   */
  float quantization_error(const float* x, int bmu_index) {
    float proto[INPUT_DIM];
    quantize(bmu_index, proto);
    float sq = 0.0f;
    for (int j = 0; j < 2; j++) {
      float d = x[j] - proto[j];
      sq += d * d;
    }
    return sqrtf(sq);
  }
};